services:
  node_3:
    image: quorumengineering/quorum
    restart: unless-stopped
    ports:
      - "30303:30303/tcp"
      - "8545:8545"
      - "8546:8546"
      - "53000:53000"
      - "30301:30301/udp"
      - "9081:9081"
    volumes:
      - "./datadir:/datadir"
      - "./tessera/tessera0.ipc:/tessera.ipc"
    entrypoint: [ "sh", "-c" ]
    environment:
      - PRIVATE_CONFIG=/tessera.ipc
    command:
      [
        "geth --datadir /datadir --networkid 8989 --syncmode full --mine --miner.gasprice 0 --emitcheckpoints --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain https://remix.ethereum.org --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft"
      ]
    networks:
      quorum:
        ipv4_address: 172.23.0.2

    depends_on:
      tessera:
        condition: service_healthy
  tessera:
      image: quorumengineering/tessera
      restart: unless-stopped
      volumes:
        - './tessera:/tesseraconf'
        #- './datadir/geth.ipc:/geth.ipc'
      command:
        - --debug
        - -configfile
        - /tesseraconf/config.json
      healthcheck:
        test: ["CMD", "curl", "http://localhost:9081/upcheck"]
        interval: 5s
        timeout: 5s
        retries: 20

networks:
  quorum:
    ipam:
      config:
        - subnet: 172.23.0.0/24
